/**
 * Utility to generate a professional PDF for Purchase Orders
 */
export const generatePurchasePDF = (po: any) => {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const html = `
    <html>
      <head>
        <title>Purchase Order - ${po.item_name}</title>
        <style>
          body { font-family: 'Helvetica', sans-serif; padding: 40px; color: #333; }
          .header { border-bottom: 3px solid #3880ff; padding-bottom: 20px; margin-bottom: 30px; }
          .po-meta { display: flex; justify-content: space-between; margin-bottom: 40px; }
          table { width: 100%; border-collapse: collapse; margin-top: 20px; }
          th { background-color: #f4f5f8; padding: 12px; text-align: left; border-bottom: 2px solid #ddd; }
          td { padding: 12px; border-bottom: 1px solid #eee; }
          .footer { margin-top: 60px; font-size: 11px; color: #888; text-align: center; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 style="margin: 0; color: #3880ff;">ZVIPFUYO DIGITAL KRAAL</h1>
          <p style="margin: 5px 0;">Livestock Procurement Requisition</p>
        </div>
        
        <div class="po-meta">
          <div>
            <strong>PO Number:</strong> PO-${po.id}<br/>
            <strong>Date Generated:</strong> ${new Date().toLocaleDateString()}
          </div>
          <div style="text-align: right;">
            <strong>Status:</strong> DRAFT FOR REVIEW
          </div>
        </div>

        <table>
          <thead>
            <tr>
              <th>Description (Stock Item)</th>
              <th>Quantity Required</th>
              <th>Estimated Total</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>${po.item_name}</td>
              <td>${po.order_quantity}</td>
              <td>$${po.estimated_cost || '0.00'}</td>
            </tr>
          </tbody>
        </table>

        <div class="footer">
          <p>Generated by Zvipfuyo Inventory Control. Official stamp required for procurement.</p>
        </div>

        <script>
          window.onload = function() { window.print(); window.close(); };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(html);
  printWindow.document.close();
};